version: "3.3"

services:
  mediawiki:
    build:
      context: ./mediawiki
      dockerfile: Dockerfile
    networks:
      - wikiweb
      - wikidb
    volumes:
      - wikidata:/var/www/html
      - ./LocalSettings.php:/var/www/html/LocalSettings.php

  nginx:
    image: nginx:1.21.5-alpine
    volumes:
      - ./nginx/mediawiki.conf:/etc/nginx/nginx.conf
      - wikidata:/var/www/html
    networks:
      - wikiweb
    ports:
      - 80:80

  mediawikidb:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: wikiuser
      POSTGRES_PASSWORD: wikipass
      POSTGRES_DB: wikidb
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - wikidb

volumes:
  wikidata:
  dbdata:

networks:
  wikiweb:
  wikidb:
